version: '3'

services:
  mariadb:
    container_name: eoccoin_mariadb
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=brs_master
    command: mysqld --character_set_server=utf8mb4
    volumes:
      - ./burst_db:/var/lib/mysql
    networks:
      eocnetwork:
        aliases:
          - eoccoin_mariadb

  eoccoin:
    container_name: eoccoin
    image: sunaiying/eoccoin:latest
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8423:8423
      - 8425:8425
      - 8421:8421
    networks:
      eocnetwork:
        aliases:
          - eoccoin

networks:
  eocnetwork:
    driver: bridge
